### PR TITLE
Fix ImpulseGen MSVC conversion warning

### PR DESCRIPTION
**Pull request by colugomusic**
This fixes an extremely lengthy (several hundred lines) conversion warning that I can't figure out how to get Visual Studio to suppress, caused by the conversion from `std::function<float(int)>` to `std::function<float(float)>`.

The compiler deduces the `map(std::function<float(float)>, ...)` overload on line 40 because the second argument is of type `DSPVectorArray`.

### CODE REVIEW

**Comment by madronalabs** [comment]
But there's also a `map(std::function<float(int)> f, const DSPVectorArrayInt<ROWS> x)` in MLDSPFunctional.h, which is what should be getting called here.  So there should be no need to cast to float. Maybe the issue is with the second argument to map()? 

I'll take a look on my Windows box in a bit.

**Comment by colugomusic** [comment]
Exactly I think the `DSPVectorArray` (float) version is what gets deduced because that is what is returned by `columnIndex()` in the `ImpulseGen` constructor, so perhaps it would actually be better to add a `columnIndexInt()` or whatever which returns a `DSPVectorArrayInt`

**Comment by madronalabs** [comment]
I added the columnIndexInt(). Hopefully this fixes the Windows issue.

**Comment by colugomusic** [comment]
Yep ae87bd1 fixed the warning here. Thanks!

**Pull request closed without merging**
