### PR TITLE
fix Linux build errors

### PR DESCRIPTION
**Pull request by wrl**
just needed a few explicit includes for libc functions (and <functional>)

### CODE REVIEW

**Comment by madronalabs** [comment]
thanks! are you saying it builds on Linux now?

**Comment by wrl** [comment]
GCC nitpicks a few things so there's a warning or two, but other than that, yep!

```
wrl@north build% make
Scanning dependencies of target madronalib
[  5%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLClock.cpp.o
[ 10%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLPath.cpp.o
[ 15%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLProcFactory.cpp.o
In file included from /home/wrl/Downloads/madronalib/source/app/MLProcFactory.h:7,
                 from /home/wrl/Downloads/madronalib/source/app/MLProcFactory.cpp:2:
/home/wrl/Downloads/madronalib/source/app/MLProc.h: In member function ‘constexpr const ml::constStr& ml::constStrArray::operator[](std::size_t) const’:
/home/wrl/Downloads/madronalib/source/app/MLProc.h:72:20: warning: returning reference to temporary [-Wreturn-local-addr]
   72 |   return n < size_ ? p_[n] :
      |          ~~~~~~~~~~^~~~~~~~~
   73 |    throw std::out_of_range("");
      |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 21%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLSymbol.cpp.o
[ 26%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLText.cpp.o
[ 31%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLTextUtils.cpp.o
[ 36%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLTimer.cpp.o
[ 42%] Building CXX object CMakeFiles/madronalib.dir/source/app/MLValue.cpp.o
[ 47%] Building CXX object CMakeFiles/madronalib.dir/source/matrix/MLInterpolator.cpp.o
[ 52%] Building CXX object CMakeFiles/madronalib.dir/source/matrix/MLMatrix.cpp.o
[ 57%] Building CXX object CMakeFiles/madronalib.dir/source/procs/MLProcMultiply.cpp.o
In file included from /home/wrl/Downloads/madronalib/source/app/MLProcFactory.h:7,
                 from /home/wrl/Downloads/madronalib/source/procs/MLProcMultiply.h:8,
                 from /home/wrl/Downloads/madronalib/source/procs/MLProcMultiply.cpp:2:
/home/wrl/Downloads/madronalib/source/app/MLProc.h: In member function ‘constexpr const ml::constStr& ml::constStrArray::operator[](std::size_t) const’:
/home/wrl/Downloads/madronalib/source/app/MLProc.h:72:20: warning: returning reference to temporary [-Wreturn-local-addr]
   72 |   return n < size_ ? p_[n] :
      |          ~~~~~~~~~~^~~~~~~~~
   73 |    throw std::out_of_range("");
      |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 63%] Building CXX object CMakeFiles/madronalib.dir/external/aes256/aes256.cpp.o
[ 68%] Linking CXX static library libmadrona.a
[ 68%] Built target madronalib
Scanning dependencies of target ReverbExample
[ 73%] Building CXX object CMakeFiles/ReverbExample.dir/examples/source/reverb.cpp.o
[ 78%] Building CXX object CMakeFiles/ReverbExample.dir/external/rtaudio/RtAudio.cpp.o
[ 84%] Linking CXX executable bin/ReverbExample
NSMicrophoneUsageDescription
This app requires microphone access.
grep: /home/wrl/Downloads/madronalib/build/bin//ReverbExample.app/Contents/Info.plist: No such file or directory
fixing info.plist...
Can't open /home/wrl/Downloads/madronalib/build/bin//ReverbExample.app/Contents/Info.plist: No such file or directory.
[ 84%] Built target ReverbExample
Scanning dependencies of target SineExample
[ 89%] Building CXX object CMakeFiles/SineExample.dir/examples/source/sine.cpp.o
[ 94%] Building CXX object CMakeFiles/SineExample.dir/external/rtaudio/RtAudio.cpp.o
[100%] Linking CXX executable bin/SineExample
NSMicrophoneUsageDescription
This app requires microphone access.
grep: /home/wrl/Downloads/madronalib/build/bin//SineExample.app/Contents/Info.plist: No such file or directory
fixing info.plist...
Can't open /home/wrl/Downloads/madronalib/build/bin//SineExample.app/Contents/Info.plist: No such file or directory.
[100%] Built target SineExample
wrl@north build% 
```

**Comment by rncar** [comment]
Aalto for linux ... pleaaaaaase !!

**Comment by madronalabs** [comment]
super! did you try running SineExample? I guess you will need to pick the right RtAudio flag for your Linux audio system of choice, in CMake.

I'm excited to grab a Linux box or maybe dual-boot my workstation and join in the fun here when I can. Appreciate the help! 

Yes to Aalto for linux!

**Pull request merged**
